from os import error
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys
from PyQt5.QtWidgets import (QWidget, QLabel, QCompleter, QLineEdit, 
    QHBoxLayout, QApplication)
from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox
import datetime
from reportlab.pdfgen import canvas
import webbrowser
global B
B=0
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 581)
        Form.setFixedSize(660,581)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/TCS-01.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 661, 581))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.widget = QtWidgets.QWidget(self.page)
        self.widget.setGeometry(QtCore.QRect(160, 230, 341, 261))
        self.widget.setStyleSheet("background-color: rgb(191, 20, 0);")
        self.widget.setObjectName("widget")
        self.user = QtWidgets.QLabel(self.widget)
        self.user.setGeometry(QtCore.QRect(20, 60, 121, 41))
        self.user.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.user.setObjectName("user")
        self.pass1 = QtWidgets.QLabel(self.widget)
        self.pass1.setGeometry(QtCore.QRect(20, 140, 111, 41))
        self.pass1.setStyleSheet("font: 75 16pt \"Times New Roman\";")
        self.pass1.setObjectName("pass")
        self.useredit = QtWidgets.QLineEdit(self.widget)
        self.useredit.setGeometry(QtCore.QRect(182, 59, 141, 41))
        self.useredit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.useredit.setObjectName("useredit")
        self.passedit = QtWidgets.QLineEdit(self.widget)
        self.passedit.setGeometry(QtCore.QRect(180, 140, 141, 41))
        self.passedit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.passedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passedit.setObjectName("passedit")
        self.loginbut = QtWidgets.QPushButton(self.widget)
        self.loginbut.setGeometry(QtCore.QRect(120, 220, 101, 31))
        self.loginbut.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 85, 0);")
        self.loginbut.setObjectName("loginbut")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(220, 0, 221, 221))
        self.frame.setStyleSheet("image: url(:/newPrefix/TCS-01.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(120, 530, 461, 41))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 26pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, -9, 131, 141))
        self.frame_2.setStyleSheet("image: url(:/newPrefix/TCS-01.jpg);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.widget_2 = QtWidgets.QWidget(self.page_2)
        self.widget_2.setGeometry(QtCore.QRect(0, 430, 221, 151))
        self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
        self.widget_2.setObjectName("widget_2")
        self.Sub_line = QtWidgets.QLineEdit(self.widget_2)
        self.Sub_line.setEnabled(False)
        self.Sub_line.setGeometry(QtCore.QRect(102, 10, 101, 31))
        self.Sub_line.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.Sub_line.setObjectName("Sub_line")
        self.tax_line = QtWidgets.QLineEdit(self.widget_2)
        self.tax_line.setEnabled(False)
        self.tax_line.setGeometry(QtCore.QRect(102, 60, 101, 31))
        self.tax_line.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.tax_line.setReadOnly(True)
        self.tax_line.setObjectName("tax_line")
        self.net_line = QtWidgets.QLineEdit(self.widget_2)
        self.net_line.setEnabled(False)
        self.net_line.setGeometry(QtCore.QRect(102, 110, 101, 31))
        self.net_line.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.net_line.setObjectName("net_line")
        self.sub_label = QtWidgets.QLabel(self.widget_2)
        self.sub_label.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.sub_label.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.sub_label.setObjectName("sub_label")
        self.tax_label = QtWidgets.QLabel(self.widget_2)
        self.tax_label.setGeometry(QtCore.QRect(30, 60, 41, 31))
        self.tax_label.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.tax_label.setObjectName("tax_label")
        self.total_label = QtWidgets.QLabel(self.widget_2)
        self.total_label.setGeometry(QtCore.QRect(30, 110, 41, 31))
        self.total_label.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.total_label.setObjectName("total_label")
        self.widget_3 = QtWidgets.QWidget(self.page_2)
        self.widget_3.setGeometry(QtCore.QRect(210, 430, 231, 151))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.pay_label = QtWidgets.QLabel(self.widget_3)
        self.pay_label.setGeometry(QtCore.QRect(40, 60, 41, 31))
        self.pay_label.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.pay_label.setObjectName("pay_label")
        self.net_line_2 = QtWidgets.QLineEdit(self.widget_3)
        self.net_line_2.setEnabled(False)
        self.net_line_2.setGeometry(QtCore.QRect(112, 110, 101, 31))
        self.net_line_2.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.net_line_2.setReadOnly(False)
        self.net_line_2.setClearButtonEnabled(False)
        self.net_line_2.setObjectName("net_line_2")
        self.pay_line = QtWidgets.QLineEdit(self.widget_3)
        self.pay_line.setEnabled(False)
        self.pay_line.setGeometry(QtCore.QRect(112, 60, 101, 31))
        self.pay_line.setAutoFillBackground(False)
        self.pay_line.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(0, 0, 0);")
        self.pay_line.setText("")
        self.pay_line.setReadOnly(True)
        self.pay_line.setObjectName("pay_line")
        self.change_label = QtWidgets.QLabel(self.widget_3)
        self.change_label.setGeometry(QtCore.QRect(20, 110, 81, 31))
        self.change_label.setStyleSheet("font: 75 14pt \"Times New Roman\";")
        self.change_label.setObjectName("change_label")
        self.payment_label = QtWidgets.QLabel(self.widget_3)
        self.payment_label.setGeometry(QtCore.QRect(7, 10, 101, 31))
        self.payment_label.setStyleSheet("font: 75 11pt \"Times New Roman\";")
        self.payment_label.setObjectName("payment_label")
        self.cash_comb = QtWidgets.QComboBox(self.widget_3)
        self.cash_comb.setEnabled(False)
        self.cash_comb.setGeometry(QtCore.QRect(112, 10, 101, 31))
        self.cash_comb.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0,0,0);")
        self.cash_comb.setObjectName("cash_comb")
        self.cash_comb.addItem("")
        self.cash_comb.addItem("")
        self.widget_4 = QtWidgets.QWidget(self.page_2)
        self.widget_4.setGeometry(QtCore.QRect(440, 430, 221, 151))
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.paybut = QtWidgets.QPushButton(self.widget_4)
        self.paybut.setGeometry(QtCore.QRect(0, 0, 221, 71))
        self.paybut.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.paybut.setObjectName("paybut")
        self.resetbut = QtWidgets.QPushButton(self.widget_4)
        self.resetbut.setGeometry(QtCore.QRect(0, 70, 221, 81))
        self.resetbut.setStyleSheet("font: 75 20pt \"Times New Roman\";\n"
"background-color: rgb(206, 67, 67);")
        self.resetbut.setObjectName("resetbut")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setGeometry(QtCore.QRect(439, 190, 221, 241))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.cal1_2 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_2.setGeometry(QtCore.QRect(0, 180, 111, 61))
        self.cal1_2.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_2.setObjectName("cal1_2")
        self.cal1_3 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_3.setGeometry(QtCore.QRect(110, 180, 111, 61))
        self.cal1_3.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_3.setObjectName("cal1_3")
        self.cal1 = QtWidgets.QPushButton(self.frame_3)
        self.cal1.setGeometry(QtCore.QRect(0, 120, 76, 61))
        self.cal1.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1.setObjectName("cal1")
        self.cal1_4 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_4.setGeometry(QtCore.QRect(75, 120, 76, 61))
        self.cal1_4.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_4.setObjectName("cal1_4")
        self.cal1_5 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_5.setGeometry(QtCore.QRect(150, 120, 76, 61))
        self.cal1_5.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_5.setObjectName("cal1_5")
        self.cal1_6 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_6.setGeometry(QtCore.QRect(0, 60, 76, 61))
        self.cal1_6.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_6.setObjectName("cal1_6")
        self.cal1_7 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_7.setGeometry(QtCore.QRect(75, 60, 76, 61))
        self.cal1_7.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_7.setObjectName("cal1_7")
        self.cal1_8 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_8.setGeometry(QtCore.QRect(150, 60, 76, 61))
        self.cal1_8.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_8.setObjectName("cal1_8")
        self.cal1_9 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_9.setGeometry(QtCore.QRect(0, 0, 76, 61))
        self.cal1_9.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_9.setObjectName("cal1_9")
        self.cal1_10 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_10.setGeometry(QtCore.QRect(75, 0, 76, 61))
        self.cal1_10.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_10.setObjectName("cal1_10")
        self.cal1_11 = QtWidgets.QPushButton(self.frame_3)
        self.cal1_11.setGeometry(QtCore.QRect(150, 0, 76, 61))
        self.cal1_11.setStyleSheet("font: 75 28pt \"Times New Roman\";\n"
"background-color: rgb(85, 255, 255);")
        self.cal1_11.setObjectName("cal1_11")
        self.tableWidget = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget.setGeometry(QtCore.QRect(440, 0, 221, 141))
        self.tableWidget.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(15)
        self.tableWidget.verticalHeader().setMinimumSectionSize(15)
        self.quanedit = QtWidgets.QLineEdit(self.page_2)
        self.quanedit.setEnabled(False)
        self.quanedit.setGeometry(QtCore.QRect(330, 77, 101, 28))
        self.quanedit.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0,0,0);")
        self.quanedit.setObjectName("quanedit")
        self.addqua = QtWidgets.QPushButton(self.page_2)
        self.addqua.setGeometry(QtCore.QRect(450, 150, 81, 31))
        self.addqua.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 75 16pt \"Times New Roman\";")
        self.addqua.setObjectName("addqua")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(330, 110, 111, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(313, 0, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(130, 50, 96, 81))
        self.pushButton.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/capp-01.jpg);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 159, 88, 71))
        self.pushButton_2.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/download1.jpg);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(88, 159, 88, 71))
        self.pushButton_3.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/download (2).jpg);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(176, 159, 88, 71))
        self.pushButton_4.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/download (3).jpg);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(264, 159, 88, 71))
        self.pushButton_5.setStyleSheet("\n"
"image: url(:/newPrefix/IMAGES FOR TCS/balcktea.jpg);")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 259, 88, 71))
        self.pushButton_6.setStyleSheet("\n"
"image: url(:/newPrefix/IMAGES FOR TCS/tea.jpg);")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_8.setGeometry(QtCore.QRect(176, 259, 88, 71))
        self.pushButton_8.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/vanilla hot.jpg);")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_9.setGeometry(QtCore.QRect(84, 259, 88, 71))
        self.pushButton_9.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/lemontea.jpg);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_10.setGeometry(QtCore.QRect(352, 159, 88, 71))
        self.pushButton_10.setStyleSheet("\n"
"image: url(:/newPrefix/IMAGES FOR TCS/greentea.jpg);")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 359, 88, 71))
        self.pushButton_12.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/fries.jpg);")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_13.setGeometry(QtCore.QRect(88, 359, 88, 71))
        self.pushButton_13.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/donuts.jpg);")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_14.setGeometry(QtCore.QRect(264, 359, 88, 71))
        self.pushButton_14.setStyleSheet("image:url(:/newPrefix/IMAGES FOR TCS/100-1002017_chicken-mayo-sandwich-png.png)")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_15.setGeometry(QtCore.QRect(176, 359, 88, 71))
        self.pushButton_15.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/cupcake.jpg);")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_16.setGeometry(QtCore.QRect(352, 359, 88, 71))
        self.pushButton_16.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/pastries.jpg);")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_17.setGeometry(QtCore.QRect(226, 50, 96, 81))
        self.pushButton_17.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/download.jpg);\n"
"")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(130, 0, 192, 31))
        self.label.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.amount1 = QtWidgets.QLineEdit(self.page_2)
        self.amount1.setEnabled(False)
        self.amount1.setGeometry(QtCore.QRect(160, 110, 41, 21))
        self.amount1.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount1.setText("")
        self.amount1.setReadOnly(True)
        self.amount1.setObjectName("amount1")
        self.amount2 = QtWidgets.QLineEdit(self.page_2)
        self.amount2.setEnabled(False)
        self.amount2.setGeometry(QtCore.QRect(250, 105, 41, 25))
        self.amount2.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount2.setText("")
        self.amount2.setReadOnly(True)
        self.amount2.setObjectName("amount2")
        self.amount3 = QtWidgets.QLineEdit(self.page_2)
        self.amount3.setEnabled(False)
        self.amount3.setGeometry(QtCore.QRect(20, 210, 44, 21))
        self.amount3.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount3.setText("")
        self.amount3.setReadOnly(True)
        self.amount3.setObjectName("amount3")
        self.sub_label_3 = QtWidgets.QLabel(self.page_2)
        self.sub_label_3.setGeometry(QtCore.QRect(140, 32, 71, 20))
        self.sub_label_3.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_3.setObjectName("sub_label_3")
        self.sub_label_4 = QtWidgets.QLabel(self.page_2)
        self.sub_label_4.setGeometry(QtCore.QRect(15, 138, 61, 21))
        self.sub_label_4.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_4.setObjectName("sub_label_4")
        self.sub_label_5 = QtWidgets.QLabel(self.page_2)
        self.sub_label_5.setGeometry(QtCore.QRect(110, 138, 41, 21))
        self.sub_label_5.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_5.setObjectName("sub_label_5")
        self.amount4 = QtWidgets.QLineEdit(self.page_2)
        self.amount4.setEnabled(False)
        self.amount4.setGeometry(QtCore.QRect(110, 210, 44, 21))
        self.amount4.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount4.setText("")
        self.amount4.setReadOnly(True)
        self.amount4.setObjectName("amount4")
        self.sub_label_6 = QtWidgets.QLabel(self.page_2)
        self.sub_label_6.setGeometry(QtCore.QRect(181, 138, 81, 21))
        self.sub_label_6.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_6.setObjectName("sub_label_6")
        self.amount5 = QtWidgets.QLineEdit(self.page_2)
        self.amount5.setEnabled(False)
        self.amount5.setGeometry(QtCore.QRect(200, 210, 44, 21))
        self.amount5.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount5.setText("")
        self.amount5.setReadOnly(True)
        self.amount5.setObjectName("amount5")
        self.sub_label_7 = QtWidgets.QLabel(self.page_2)
        self.sub_label_7.setGeometry(QtCore.QRect(278, 138, 61, 21))
        self.sub_label_7.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_7.setObjectName("sub_label_7")
        self.amount6 = QtWidgets.QLineEdit(self.page_2)
        self.amount6.setEnabled(False)
        self.amount6.setGeometry(QtCore.QRect(290, 210, 44, 21))
        self.amount6.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount6.setText("")
        self.amount6.setReadOnly(True)
        self.amount6.setObjectName("amount6")
        self.sub_label_8 = QtWidgets.QLabel(self.page_2)
        self.sub_label_8.setGeometry(QtCore.QRect(363, 138, 61, 21))
        self.sub_label_8.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_8.setObjectName("sub_label_8")
        self.amount7 = QtWidgets.QLineEdit(self.page_2)
        self.amount7.setEnabled(False)
        self.amount7.setGeometry(QtCore.QRect(374, 210, 44, 21))
        self.amount7.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount7.setText("")
        self.amount7.setReadOnly(True)
        self.amount7.setObjectName("amount7")
        self.sub_label_9 = QtWidgets.QLabel(self.page_2)
        self.sub_label_9.setGeometry(QtCore.QRect(35, 230, 21, 31))
        self.sub_label_9.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_9.setObjectName("sub_label_9")
        self.amount9 = QtWidgets.QLineEdit(self.page_2)
        self.amount9.setEnabled(False)
        self.amount9.setGeometry(QtCore.QRect(110, 310, 44, 21))
        self.amount9.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount9.setText("")
        self.amount9.setReadOnly(True)
        self.amount9.setObjectName("amount9")
        self.sub_label_10 = QtWidgets.QLabel(self.page_2)
        self.sub_label_10.setGeometry(QtCore.QRect(360, 230, 71, 31))
        self.sub_label_10.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_10.setObjectName("sub_label_10")
        self.sub_label_11 = QtWidgets.QLabel(self.page_2)
        self.sub_label_11.setGeometry(QtCore.QRect(95, 230, 61, 31))
        self.sub_label_11.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_11.setObjectName("sub_label_11")
        self.amount8 = QtWidgets.QLineEdit(self.page_2)
        self.amount8.setEnabled(False)
        self.amount8.setGeometry(QtCore.QRect(20, 310, 44, 21))
        self.amount8.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount8.setText("")
        self.amount8.setReadOnly(True)
        self.amount8.setObjectName("amount8")
        self.sub_label_13 = QtWidgets.QLabel(self.page_2)
        self.sub_label_13.setGeometry(QtCore.QRect(175, 230, 91, 31))
        self.sub_label_13.setStyleSheet("font: 75 6pt \"Times New Roman\";")
        self.sub_label_13.setObjectName("sub_label_13")
        self.amount10 = QtWidgets.QLineEdit(self.page_2)
        self.amount10.setEnabled(False)
        self.amount10.setGeometry(QtCore.QRect(200, 310, 44, 21))
        self.amount10.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount10.setText("")
        self.amount10.setReadOnly(True)
        self.amount10.setObjectName("amount10")
        self.sub_label_14 = QtWidgets.QLabel(self.page_2)
        self.sub_label_14.setGeometry(QtCore.QRect(30, 330, 31, 30))
        self.sub_label_14.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_14.setObjectName("sub_label_14")
        self.amount16 = QtWidgets.QLineEdit(self.page_2)
        self.amount16.setEnabled(False)
        self.amount16.setGeometry(QtCore.QRect(290, 410, 44, 21))
        self.amount16.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount16.setText("")
        self.amount16.setReadOnly(True)
        self.amount16.setObjectName("amount16")
        self.sub_label_15 = QtWidgets.QLabel(self.page_2)
        self.sub_label_15.setGeometry(QtCore.QRect(370, 330, 51, 30))
        self.sub_label_15.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_15.setObjectName("sub_label_15")
        self.sub_label_16 = QtWidgets.QLabel(self.page_2)
        self.sub_label_16.setGeometry(QtCore.QRect(275, 330, 71, 30))
        self.sub_label_16.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_16.setObjectName("sub_label_16")
        self.sub_label_17 = QtWidgets.QLabel(self.page_2)
        self.sub_label_17.setGeometry(QtCore.QRect(105, 333, 41, 21))
        self.sub_label_17.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_17.setObjectName("sub_label_17")
        self.amount14 = QtWidgets.QLineEdit(self.page_2)
        self.amount14.setEnabled(False)
        self.amount14.setGeometry(QtCore.QRect(110, 410, 44, 21))
        self.amount14.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount14.setText("")
        self.amount14.setReadOnly(True)
        self.amount14.setObjectName("amount14")
        self.amount13 = QtWidgets.QLineEdit(self.page_2)
        self.amount13.setEnabled(False)
        self.amount13.setGeometry(QtCore.QRect(20, 410, 44, 21))
        self.amount13.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount13.setText("")
        self.amount13.setReadOnly(True)
        self.amount13.setObjectName("amount13")
        self.sub_label_18 = QtWidgets.QLabel(self.page_2)
        self.sub_label_18.setGeometry(QtCore.QRect(188, 330, 61, 30))
        self.sub_label_18.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_18.setObjectName("sub_label_18")
        self.amount15 = QtWidgets.QLineEdit(self.page_2)
        self.amount15.setEnabled(False)
        self.amount15.setGeometry(QtCore.QRect(200, 410, 44, 21))
        self.amount15.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount15.setText("")
        self.amount15.setReadOnly(True)
        self.amount15.setObjectName("amount15")
        self.amount17 = QtWidgets.QLineEdit(self.page_2)
        self.amount17.setEnabled(False)
        self.amount17.setGeometry(QtCore.QRect(370, 410, 44, 21))
        self.amount17.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount17.setText("")
        self.amount17.setReadOnly(True)
        self.amount17.setObjectName("amount17")
        self.sub_label_19 = QtWidgets.QLabel(self.page_2)
        self.sub_label_19.setGeometry(QtCore.QRect(240, 32, 71, 20))
        self.sub_label_19.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_19.setObjectName("sub_label_19")
        self.quanedit_2 = QtWidgets.QLineEdit(self.page_2)
        self.quanedit_2.setEnabled(False)
        self.quanedit_2.setGeometry(QtCore.QRect(330, 40, 101, 28))
        self.quanedit_2.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(85, 255, 255);")
        self.quanedit_2.setObjectName("quanedit_2")
        self.quanedit_3 = QtWidgets.QLineEdit(self.page_2)
        self.quanedit_3.setEnabled(False)
        self.quanedit_3.setGeometry(QtCore.QRect(330, 3, 101, 28))
        self.quanedit_3.setStyleSheet("font: 75 14pt \"Times New Roman\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgb(85, 255, 255);")
        self.quanedit_3.setObjectName("quanedit_3")
        self.sub_label_12 = QtWidgets.QLabel(self.page_2)
        self.sub_label_12.setGeometry(QtCore.QRect(270, 230, 81, 31))
        self.sub_label_12.setStyleSheet("font: 75 7.5pt \"Times New Roman\";")
        self.sub_label_12.setObjectName("sub_label_12")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_11.setGeometry(QtCore.QRect(350, 260, 88, 71))
        self.pushButton_11.setStyleSheet("image: url(:/newPrefix/IMAGES FOR TCS/cheesecake.jpg);")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.amount12 = QtWidgets.QLineEdit(self.page_2)
        self.amount12.setEnabled(False)
        self.amount12.setGeometry(QtCore.QRect(370, 310, 44, 21))
        self.amount12.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount12.setText("")
        self.amount12.setReadOnly(True)
        self.amount12.setObjectName("amount12")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_7.setGeometry(QtCore.QRect(260, 260, 88, 71))
        self.pushButton_7.setStyleSheet("\n"
"image: url(:/newPrefix/IMAGES FOR TCS/hotchocolate.jpg);")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.amount11 = QtWidgets.QLineEdit(self.page_2)
        self.amount11.setEnabled(False)
        self.amount11.setGeometry(QtCore.QRect(285, 310, 44, 21))
        self.amount11.setStyleSheet("font: 75 16pt \"Times New Roman\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.amount11.setText("")
        self.amount11.setReadOnly(True)
        self.amount11.setObjectName("amount11")
        self.radioButton = QtWidgets.QRadioButton(self.page_2)
        self.radioButton.setGeometry(QtCore.QRect(560, 146, 81, 21))
        self.radioButton.setStyleSheet("font: 20pt \"Times New Roman\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_2.setGeometry(QtCore.QRect(560, 169, 71, 21))
        self.radioButton_2.setStyleSheet("font: 20pt \"Times New Roman\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TCS"))
        self.user.setText(_translate("Form", "USERNAME"))
        self.pass1.setText(_translate("Form", "PASSWORD"))
        self.useredit.setPlaceholderText(_translate("Form", "USERNAME"))
        self.passedit.setPlaceholderText(_translate("Form", "PASSWORD"))
        self.loginbut.setText(_translate("Form", "LOGIN"))
        self.loginbut.setShortcut(_translate("Form", "Return"))
        self.label_2.setText(_translate("Form", "MADE BY MSY SOFTWARES"))
        self.tax_line.setText(_translate("Form", "      13%"))
        self.sub_label.setText(_translate("Form", "Sub-Total"))
        self.tax_label.setText(_translate("Form", "Tax"))
        self.total_label.setText(_translate("Form", "Total"))
        self.pay_label.setText(_translate("Form", "PAY"))
        self.change_label.setText(_translate("Form", "CHANGE"))
        self.payment_label.setText(_translate("Form", "Payment Method"))
        self.cash_comb.setItemText(0, _translate("Form", "CASH"))
        self.cash_comb.setItemText(1, _translate("Form", "CARD"))
        self.paybut.setText(_translate("Form", "PAY"))
        self.resetbut.setText(_translate("Form", "RESET"))
        self.cal1_2.setText(_translate("Form", "0"))
        self.cal1_3.setText(_translate("Form", "C"))
        self.cal1.setText(_translate("Form", "1"))
        self.cal1_4.setText(_translate("Form", "2"))
        self.cal1_5.setText(_translate("Form", "3"))
        self.cal1_6.setText(_translate("Form", "4"))
        self.cal1_7.setText(_translate("Form", "5"))
        self.cal1_8.setText(_translate("Form", "6"))
        self.cal1_9.setText(_translate("Form", "7"))
        self.cal1_10.setText(_translate("Form", "8"))
        self.cal1_11.setText(_translate("Form", "9"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "PRICE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "TOTAL"))
        self.addqua.setText(_translate("Form", "ADD"))
        self.label.setText(_translate("Form", "             MENU"))
        self.sub_label_3.setText(_translate("Form", "CAPPUCCINO"))
        self.sub_label_4.setText(_translate("Form", "ESSPRESSO"))
        self.sub_label_5.setText(_translate("Form", "LATTE"))
        self.sub_label_6.setText(_translate("Form", "BLACK COFFEE"))
        self.sub_label_7.setText(_translate("Form", "BLACK TEA"))
        self.sub_label_8.setText(_translate("Form", "GREEN TEA"))
        self.sub_label_9.setText(_translate("Form", "TEA"))
        self.sub_label_10.setText(_translate("Form", "CHESSECAKE"))
        self.sub_label_11.setText(_translate("Form", "LEMON TEA"))
        self.sub_label_13.setText(_translate("Form", "VANILLA CHOCOLATE"))
        self.sub_label_14.setText(_translate("Form", "FRIES"))
        self.sub_label_15.setText(_translate("Form", "PASTRIES"))
        self.sub_label_16.setText(_translate("Form", "CG SANDWICH"))
        self.sub_label_17.setText(_translate("Form", "DONUTS"))
        self.sub_label_18.setText(_translate("Form", "CUPCAKES"))
        self.sub_label_19.setText(_translate("Form", "AMERICANO"))
        self.sub_label_12.setText(_translate("Form", "HOT CHOOLATE"))
        self.radioButton.setText(_translate("Form", "ADD"))
        self.radioButton_2.setText(_translate("Form", "PAY"))
######    (:     BUTTON   CONNECTION     :)     ####        
        self.cal1_2.clicked.connect(self.but0)
        self.cal1.clicked.connect(self.but1)
        self.cal1_4.clicked.connect(self.but2)
        self.cal1_5.clicked.connect(self.but3)
        self.cal1_6.clicked.connect(self.but4)
        self.cal1_7.clicked.connect(self.but5)
        self.cal1_8.clicked.connect(self.but6)
        self.cal1_9.clicked.connect(self.but7)
        self.cal1_10.clicked.connect(self.but8)
        self.cal1_11.clicked.connect(self.but9)
        self.loginbut.clicked.connect(self.login)
        self.loginbut.clicked.connect(self.itemload)
        self.addqua.clicked.connect(self.insertdata)
        self.addqua.clicked.connect(self.loaddata)
#########################################################
        self.pushButton.clicked.connect(self.capp)
        self.pushButton_17.clicked.connect(self.ameri)
        self.pushButton_2.clicked.connect(self.espress)
        self.pushButton_3.clicked.connect(self.latte)
        self.pushButton_4.clicked.connect(self.bc)
        self.pushButton_5.clicked.connect(self.bt)
        self.pushButton_10.clicked.connect(self.gt)
        self.pushButton_6.clicked.connect(self.tea)
        self.pushButton_9.clicked.connect(self.lt)
        self.pushButton_8.clicked.connect(self.vc)
        self.pushButton_7.clicked.connect(self.ht)
        self.pushButton_11.clicked.connect(self.cc)
        self.pushButton_12.clicked.connect(self.fries)
        self.pushButton_13.clicked.connect(self.don)
        self.pushButton_15.clicked.connect(self.cup)
        self.pushButton_14.clicked.connect(self.cgs)
        self.pushButton_16.clicked.connect(self.past)
############################################################
        self.paybut.clicked.connect(self.pay)
        self.cal1_3.clicked.connect(self.cleart)
        self.resetbut.clicked.connect(self.save)
        self.resetbut.clicked.connect(self.reset)

######        FUNCTIONS              #############
    def login(self):
           u1=self.useredit.text()
           pass1=self.passedit.text()
           try:
                   conn = sqlite3.connect('TCS.db')
                   cursor = conn.cursor()
                   sql = 'SELECT * FROM LOGIN WHERE USER = ? and PASSWORD = ?;'
                   cursor.execute(sql,(u1,pass1))
                   row=cursor.fetchone()
                   if row==None:
                           msg = QMessageBox()
                           msg.setIcon(QMessageBox.Critical)
                           msg.setText("USERNAME OR PASSWORD IS INCORRECT")
                           msg.setWindowTitle("XMART")
                           msg.exec_()
                           self.passedit.setText("")
                   else:
                           msg = QMessageBox()
                           msg.setIcon(QMessageBox.Information)
                           msg.setText("SUCCESSFULLY LOGGED IN")
                           msg.setWindowTitle("XMART")
                           msg.exec_()
                           self.useredit.setText("")
                           self.passedit.setText("")
                           self.stackedWidget.setCurrentIndex(1)
           except Exception as error:
                   print(error)
    def itemload(self):
            conn = sqlite3.connect('TCS.db')
            cursor = conn.cursor()
            sql = ('SELECT PRICE FROM FOOD')
            cursor.execute(sql,)
            b=(cursor.fetchall())
            data=[datum[0] for datum in b]
            ##print(data)
            self.amount1.setText(data[0]) 
            self.amount2.setText(data[1])
            self.amount3.setText(data[2])
            self.amount4.setText(data[3])
            self.amount5.setText(data[4])
            self.amount6.setText(data[5])
            self.amount7.setText(data[6])
            self.amount8.setText(data[7])
            self.amount9.setText(data[8])
            self.amount10.setText(data[9])
            self.amount11.setText(data[10])
            self.amount12.setText(data[11])
            self.amount13.setText(data[12])
            self.amount14.setText(data[13])
            self.amount15.setText(data[14])
            self.amount16.setText(data[15])
            self.amount17.setText(data[16])
            conn.commit()
            conn.close()
    def save(self):
        global C
        x = datetime.datetime.now()
        datte=x.strftime("%x")
        try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql=("INSERT INTO SALES(SALE,DATE) VALUES(?,?);")
                cursor.execute(sql,(C,datte))
                conn.commit()
                conn.close()
        except Exception as error:
                print(error)
    def reset(self):
            self.pay_line.setText("")
            self.net_line_2.setText("")
            self.Sub_line.setText("")
            self.net_line.setText("")
            try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql=("DELETE FROM DATA")
                result=cursor.execute(sql)
                conn.commit()
                conn.close()
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql=("SELECT * FROM DATA")
                result=cursor.execute(sql)
                self.tableWidget.setRowCount(0)
                for row_number, row_data in enumerate(result):
                        self.tableWidget.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                self.tableWidget.setItem(row_number,column_number, QtWidgets.QTableWidgetItem(str(data)))
                self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                conn.commit()
                conn.close()
            except Exception as error:
                print(error)
    def cleart(self):
            self.pay_line.setText("")
            self.quanedit.setText("")
    def pay(self):
            to=self.net_line.text()
            paym=self.pay_line.text()
            sub=self.net_line.text()
            try:
                if paym != "" and int(paym) > int(sub):    
                   tot=int(paym)-int(to)
                   self.net_line_2.setText(str(tot))
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("ENTER PAYMENT AMOUNT OR CORRECT AMOUNT")
                   msg.setWindowTitle("TCS")
                   msg.exec_() 
            except Exception as error:
                print(error)
    def but0(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                   self.quanedit.setText(text + "0")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "0")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but1(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "1")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "1")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but2(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "2")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "2")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but3(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "3")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "3")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but4(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "4")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "4")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but5(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "5")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "5")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but6(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "6")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "6")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but7(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "7")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "7")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but8(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "8")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "8")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_()
            except Exception as error:
                print(error)
    def but9(self):
            try:
                if self.radioButton.isChecked()== True:
                   text = self.quanedit.text()
                   self.quanedit.setText(text + "9")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                elif self.radioButton_2.isChecked()== True:
                   text = self.pay_line.text()
                   self.pay_line.setText(text + "9")
                   self.widget_3.setStyleSheet("background-color: rgb(255, 67, 10);")
                   self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
                else:
                   msg = QMessageBox()
                   msg.setIcon(QMessageBox.Critical)
                   msg.setText("FIRST SELECT WHERE TO ADD")
                   msg.setWindowTitle("TCS")
                   msg.exec_() 
            except Exception as error:
                print(error)
    def insertdata(self):
            name=self.quanedit_3.text()
            price=self.quanedit_2.text()
            quantity=self.quanedit.text()
            try:
                if name and price and quantity != "":
                        global B
                        global C
                        A=int(price)*int(quantity)
                        B=B+A
                        C=round(B+(B*13/100))
                        A=str(A)
                        conn = sqlite3.connect('TCS.db')
                        cursor = conn.cursor()
                        sql=("INSERT INTO DATA(NAME,PRICE,Quantity,TOTAL) VALUES(?,?,?,?);")
                        cursor.execute(sql,(name,price,quantity,A))
                        conn.commit()
                        conn.close()
                        self.Sub_line.setText(str(B))
                        self.net_line.setText(str(C))
                        self.quanedit_3.setText("")
                        self.quanedit_2.setText("")
                        self.quanedit.setText("")
                else:
                        msg = QMessageBox()
                        msg.setIcon(QMessageBox.Critical)
                        msg.setText("CHECK AGAIN")
                        msg.setWindowTitle("TCS")
                        msg.exec_() 
            except Exception as error:
                print(error)

    def loaddata(self):
            try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql=("SELECT * FROM DATA")
                result=cursor.execute(sql)
                self.tableWidget.setRowCount(0)
                for row_number, row_data in enumerate(result):
                        self.tableWidget.insertRow(row_number)
                        for column_number, data in enumerate(row_data):
                                        self.tableWidget.setItem(row_number,column_number, QtWidgets.QTableWidgetItem(str(data)))
                conn.commit()
                conn.close()
            except Exception as error:
                print("LOAD",error)
    def capp(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "001"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)
    def ameri(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "002"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)
    def espress(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "003"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def latte(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "004"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def bc(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "005"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def bt(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "006"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def gt(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "007"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def tea(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "008"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def lt(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "009"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def vc(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "010"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def ht(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "011"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def cc(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "012"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def fries(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "013"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def don(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "014"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def cup(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "015"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def cgs(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "016"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   
    def past(self):
           name=self.quanedit_3.text()
           price=self.quanedit_2.text()
           try:
                conn = sqlite3.connect('TCS.db')
                cursor = conn.cursor()
                sql = ('SELECT * FROM FOOD WHERE PR_ID = "017"')
                cursor.execute(sql,)                    
                b=cursor.fetchall()
                self.quanedit_3.setText(b[0][1])
                self.quanedit_2.setText(b[0][2])
                conn.commit()
                conn.close()
           except Exception as error:
                print(error)   




import TCS_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
